@echo off
REN BuiltIn00.bmp New.bmp
REN BuiltIn01.bmp Open.bmp
REN BuiltIn02.bmp Save.bmp
REN BuiltIn03.bmp Undo.bmp
REN BuiltIn04.bmp Redo.bmp
REN BuiltIn05.bmp Cut.bmp
REN BuiltIn06.bmp Copy.bmp
REN BuiltIn07.bmp Paste.bmp
REN BuiltIn08.bmp Print.bmp
REN BuiltIn09.bmp Help.bmp
REN BuiltIn10.bmp Find.bmp
REN BuiltIn11.bmp SaveAll.bmp
REN BuiltIn12.bmp SaveSesn.bmp
REN BuiltIn13.bmp NewSesn.bmp
REN BuiltIn14.bmp LoadSesn.bmp
REN BuiltIn15.bmp RunScript.bmp
REN BuiltIn16.bmp Replace.bmp
REN BuiltIn17.bmp WinClose.bmp
REN BuiltIn18.bmp WinMax.bmp
REN BuiltIn19.bmp WinMin.bmp
REN BuiltIn20.bmp WinSplit.bmp
REN BuiltIn21.bmp Shell.bmp
REN BuiltIn22.bmp FindPrev.bmp
REN BuiltIn23.bmp FindNext.bmp
REN BuiltIn24.bmp FindHelp.bmp
REN BuiltIn25.bmp Make.bmp
REN BuiltIn26.bmp TagJump.bmp
REN BuiltIn27.bmp RunCtags.bmp
REN BuiltIn28.bmp WinVSplit.bmp
REN BuiltIn29.bmp WinMaxWidth.bmp
REN BuiltIn30.bmp WinMinWidth.bmp
